# Generated by Django 4.0.2 on 2022-02-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kindpng.com%2Fimgv%2FiihmoJi_alt-text-placeholder-convenience-food-hd-png-download%2F&psig=AOvVaw1UJwrmu3lWVKmRk7QGlMac&ust=1646052201487000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCNieqLj0n_YCFQAAAAAdAAAAABAO', max_length=500),
        ),
    ]
