# Generated by Django 4.0.2 on 2022-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.dirtyapronrecipes.com/wp-content/uploads/2015/10/food-placeholder.png', max_length=500),
        ),
    ]
