# Generated by Django 4.0.2 on 2022-03-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_user',
            new_name='item_created_by',
        ),
    ]
